### ISSUE TITLE
Vorschau auch ohne vorheriges Drucken

### ISSUE THREAD

**Issue by cod3monk** [fau-fablab/etiketten#11]

**Comment by sedrubal** [comment]
Vorschau ist sinnvoll, aber nachdem das Project so wirr ist, würde ich es nicht schaffen, vernünftige Vorschauen mit weniger als 1 Tag Aufwand rein zu frickeln. Drum geht es jetzt nur beim Drucken von einzelnen OERP-Produkt Etiketten. Wenn man das mal vernünftig machen will, sollte man das alles mit Flask neu bauen... Bis dahin ist das hier ein Won't Fix
