### ISSUE TITLE
Preis verschwindet bei langen Produktnamen

### ISSUE THREAD

**Issue by cod3monk** [fau-fablab/etiketten#16]
siehe Etikett für 1251

**Comment by sedrubal** [comment]
das ist immer ein rechtes Gefrickel... mal schauen, ob sich das ohne großem Aufwand beheben lässt...

**Comment by EmJay276** [comment]
Kann man nicht einfach ne Überprüfung machen
Wenn Anzahl(Zeichen) > xy dann Zeichen = Zeichen[0:xy]?
Oder sind die einzelnen Zeichen so unterschiedlich lang?

Am 24.07.2015 um 12:17 schrieb sedrubal:

**Comment by patkan** [comment]
Ist in dem Sinne schwierig, als das das eigentliche Anordnen des Textes durch die Engine von Inkscape geschieht. Aber wenn jemand motiviert ist, könnte er mal schauen, wie viele Zeichen in etwa mindestens rein passen. (Vorlage nehmen und man einfach ausprobieren)

**Comment by sedrubal** [comment]
Wenn wir auf Monospace umstellen, können wir EmJay276's Lösung nehmen :D Aber mgmax hat das ja auch mit den freien Text Etiketten geschafft, die Breite zu bestimmen, also könnte es doch irgendwie funktionieren.

Am einfachsten wäre es allerdings eine Regel einzuführen, dass Produkt Titel nur x Buchstaben lang sein dürfen... ;)

**Comment by mgmax** [comment]
Regel: Produkttitel dürfen nur so lang sein, wie Platz auf einem Etikett ist :)
