### ISSUE TITLE
Mass Pdf Export

### ISSUE THREAD

**Issue by dbambus** [fau-fablab/etiketten#18]
Ich stehe vor dem Problem, dass ich Etiketten für Boxen mit einem Innenmaß von 52 x 52 x 60 machen will. Nun sind die Etiketten die das Skript vom ERP generiert an das Label_template gebunden und haben damit eine vorgegebene Größe. 
Da ich dieses Template nicht verändern will, um einen 80% Skale der Etiketten zu bekommen und die maximale Sichtbarkeit des gesamten Etiketts (trotz der umschlossenen Ecken) zu erreichen. Würde ich gerne die Etiketten als pdf exportieren, um diesen Skale mit der PDF zu machen. Dazu ist's für mich sehr nützlich nicht jedes einzelne Etikett über die Vorschaufunktion zu bekommen, sondern über die ERP Nummern(-bereiche) direkt die einzel-pdf exponiert zu bekommen.

**Comment by mgmax** [comment]
Das PDF hat doch mehrere Seiten, wenn du mehrere Artikelnummern eingibst (vgl. den Hilfetext auf der Website). Wenn man das potentiell nochmal braucht, wäre ein neues template trotzdem gut, dazu kannst du einfach die SVG Vorlage anpassen und mir zukommen lassen.

**Comment by mgmax** [comment]
hat sich wohl erledigt
