### ISSUE TITLE
Etikettenverschwendung

### ISSUE THREAD

**Issue by patkan** [fau-fablab/etiketten#3]
Ich habe folgenden String eingegeben: `1108 1110 1108 1104 1104 1109 1109 2222 2222 1100 1100`
Dies führte zu Leeretiketten zwischen den einzelnen Etiketten.
Ist das beabsichtigtes Verhalten?

**Comment by patkan** [comment]
Das Problem scheint aber sporadisch aufzutreten. Kann es sein, dass die Etiketten als einzelne Aufträge geschickt werden?

**Comment by mgmax** [comment]
ich stelle das ganze Ding von CUPS auf direkt per ZPL drucken um

**Comment by mgmax** [comment]
Leeretiketten sind nicht im erzeugten PDF; dieses wird als Ganzes ausgedruckt. Also liegt der Fehler nicht bei uns.
Umstellung war doch nicht nötig (ist jedoch langfristig wünschenswert). 

Rekalibrierung des Druckers (Taste lang halten bis es schnell 2x blinkt, dann loslassen) hilft, sobald dieses Problem auftritt - insbesondere nach Wechsel der Materialsorte.

**Comment by mgmax** [comment]
TODO: im Drucker-Config-Interface einstellen, dass nach PowerOn und Deckel-schließen automatisch diese Kalibrierung durchgeführt wird

**Comment by EmJay276** [comment]
DONE: Im Drucker-Config-Interface einstellen, dass nach PowerOn und Deckel-schließen automatisch diese Kalibrierung durchgeführt wird

**Comment by mgmax** [comment]
super, ich hoffe mal du hast das auch dauerhaft gespeichert :) :+1:
