### ISSUE TITLE
Datenimport verbessern

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/etiketten#5]
- korrekte Nachkommastellen bei Preisen wie 0,012 € (jetziger Code ist offensichtlich leicht kaputt)
- Preis bei unverkäuflichen Artikeln weglassen / durch "unverkäuflich" ersetzen (oder anders darstellen?)

**Comment by sedrubal** [comment]
- und das ganze beschleunigen (im Moment ist es v.A. bei Mehrfachdruck ineffizient, vllt. bring ich das noch hin)

**Comment by mgmax** [comment]
@sedrubal  schau dir mal an, ich hab einiges weitergefrickelt, bevor du die Arbeit doppelt machst...
