### ISSUE TITLE
Etiketten für ganze Bestellung ausdrucken

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/etiketten#6]
Wäre hilfreich, wenn man einfach PO00123 eingibt und dann alle (gefundenen) Artikel dieser Bestellung je 1x ausgedruckt werden

**Comment by mgmax** [comment]
@sedrubal  hättest du Lust das zu implementieren? Würde Zeit sparen, wenn mal wieder große Lieferungen ankommen.

**Comment by sedrubal** [comment]
Oh das klingt sehr vernünftig, ich mach mich mal drüber, kann aber nicht versprechen, dass das in nächster Zeit was wird...

**Comment by sedrubal** [comment]
Durch a83398749959d4b6c817bd9f2b795c2c63d12f3b sollte es jetzt möglich sein, Bestellnummern einzugeben und Etiketten für alle Artikel auszudrucken.

Allerdings weiß ich nicht, ob man das wirklich so machen will, wie ich es [hier](https://github.com/fau-fablab/etiketten/commit/a83398749959d4b6c817bd9f2b795c2c63d12f3b#diff-2ee713d58d0d5244467551be76169fd4R141) gemacht hab. Es ist unheimlich langsam für lange Bestellungen.

Dafür sind noch paar andere Features dazu gekommen ;)

Wenn einer mag, kann er es auf die ws01 pullen und testen...

**Comment by mgmax** [comment]
Du hast die viel besser verständliche, aber leider hier zu langsame 
browse-API verwendet. Ich habe es mal auf 1 min Laufzeit für die fette 
Reicheltbestellung PO00268 verbessert. Viel mehr geht nicht mehr, ohne 
den Code sehr hässlich zu machen.

Eine Stelle war unsinnig, wo du .ids() und darauf wieder browse() 
machst, anstatt einfach zu schreiben:
for line in po.order_line: # (alle solche Felder aus oerp.browse sind 
als Iterator nutzbar)
     line.product_id.sowieso

**Comment by mgmax** [comment]
Und bevor ichs vergess, natürlich vielen Dank. Das darf jetzt gerne in 
Realität ausprobiert werden. Die max_execution_time von php habe ich 
sicherheitshalber schon auf 150s erhöht :)

**Comment by sedrubal** [comment]
Genau, danke :)

Will man dann doch irgendwas mit `search()` bauen? Das hab ich nämlich noch weniger verstanden... Ich war ja heil froh, dass irgendwann `product ids` heraus gefallen sind... Verstanden hab ich nicht mal das :D
