### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/etiketten#7]
Hallo,

Ich finde die 3 Branches gerade zu unübersichtlich... welcher ist denn der Hauptbranch? Kann man den im Github mal als `default` markieren? Und benötigen wir noch die alten?

Ich arbeite mal am `gx430t-label-printer`...

**Comment by mgmax** [comment]
ja, der gx430 ist der richtige. Der Rest wird nicht mehr gepflegt und 
kann weg; alle alten Features (CSV import, mehrere pro Seite) sind 
zumindest als Kommentar auch noch im neuen Code enthalten.
