### ISSUE TITLE
Anzahl an Etiketten pro Produkt auswählbar machen

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/etiketten#8]
Man will evtl. durch eine neue Ansicht auswählen können, wie viele Etiketten pro Produkt gedruckt werden sollen.

**Comment by sedrubal** [comment]
implementiert durch 3e976dd4abbc1f274cd92c2930bc5fa0c97c35d4. Ich hab recht viel umgefrickelt, also sollte man es noch bisschen testen...

**Comment by nightvisi0n** [comment]
Habe ich gerade auf der ws01 deployed, funktioniert allerdings nicht.
Nach der Eingabe einer validen Produktnummer und dem Klick auf "Anzahl wählen" erscheint nur die Fehlermeldung "Es trat ein Fehler auf: Ungültige Eingabe oder unerlaubtes Zeichen".

**Comment by sedrubal** [comment]
ich habs nochmal umgebaut (8844c9141b43f1eb51809d66c22f207f3652aa95). Jetzt wirds mit Regex überprüft. Aber danke trdm. Den Fehler mit `sizeof` hab ich anscheinend sogar noch öfters gemacht...

Ich schieb mal den Release weiter und lösche gleich den [`v1.0 stable`](https://github.com/fau-fablab/etiketten/releases/tag/v1.0) (weil der ja kaputt ist).

**Comment by nightvisi0n** [comment]
alles klar, ist auf der ws01 jetzt geupdated - funktioniert :+1:
