### ISSUE TITLE
Vorlagen für frei Text rein frickeln

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/etiketten#9]

**Comment by mgmax** [comment]
Ich bin dabei, dafür was zu basteln. Ist mit Inkscape per Kommandozeile 
etwas schmerzhaft, aber wird bald fertig.

**Comment by sedrubal** [comment]
Cool, bin gespannt :D

**Comment by mgmax** [comment]
ist im git, muss noch getestet werden.

**Comment by sedrubal** [comment]
Das ist ja wunderbar :+1: 

Ich glaub, das sollte funktionieren.

Wenn ichs richtig verstanden hab, wird das PDF mehrmals ausgedruckt, wenn die Anzahl hochgestellt wird. Wäre es nicht schneller, wenn man das PDF gleich mit meheren Seiten erstellt und dann einmal ausdruckt?
